version: "2"
linters:
  default: standard
  enable:
    - gocritic
    - modernize
    - noctx
    - perfsprint
    - prealloc
    - revive
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
