// Code generated by bpf2go; DO NOT EDIT.
//go:build (arm64be || armbe || mips || mips64 || mips64p32 || ppc64 || s390 || s390x || sparc || sparc64) && linux

package redirect

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadXdp_redirect returns the embedded CollectionSpec for xdp_redirect.
func loadXdp_redirect() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Xdp_redirectBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdp_redirect: %w", err)
	}

	return spec, err
}

// loadXdp_redirectObjects loads xdp_redirect and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*xdp_redirectObjects
//	*xdp_redirectPrograms
//	*xdp_redirectMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadXdp_redirectObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdp_redirect()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdp_redirectSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_redirectSpecs struct {
	xdp_redirectProgramSpecs
	xdp_redirectMapSpecs
}

// xdp_redirectSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_redirectProgramSpecs struct {
	XdpRedirectProg *ebpf.ProgramSpec `ebpf:"xdp_redirect_prog"`
}

// xdp_redirectMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_redirectMapSpecs struct {
	XsksMap *ebpf.MapSpec `ebpf:"xsks_map"`
}

// xdp_redirectObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadXdp_redirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_redirectObjects struct {
	xdp_redirectPrograms
	xdp_redirectMaps
}

func (o *xdp_redirectObjects) Close() error {
	return _Xdp_redirectClose(
		&o.xdp_redirectPrograms,
		&o.xdp_redirectMaps,
	)
}

// xdp_redirectMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadXdp_redirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_redirectMaps struct {
	XsksMap *ebpf.Map `ebpf:"xsks_map"`
}

func (m *xdp_redirectMaps) Close() error {
	return _Xdp_redirectClose(
		m.XsksMap,
	)
}

// xdp_redirectPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadXdp_redirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_redirectPrograms struct {
	XdpRedirectProg *ebpf.Program `ebpf:"xdp_redirect_prog"`
}

func (p *xdp_redirectPrograms) Close() error {
	return _Xdp_redirectClose(
		p.XdpRedirectProg,
	)
}

func _Xdp_redirectClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdp_redirect_bpfeb.o
var _Xdp_redirectBytes []byte
