name: build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: canonical/cloud-init
          path: cloud-init
      - name: Install eBPF build dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -y --no-install-recommends $(cat .github/apt-packages.txt)
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      - run: goreleaser build --snapshot
      - run: mise run lint
      - run: mise run test
      - run: mise run test-conformance
        env:
          CLOUD_INIT_DIR: ${{ github.workspace }}/cloud-init
